---
- hosts: all
  tasks:
    - name: Build a schedule for Demo Job Template
      ansible.tower.tower_schedule:
        name: "Schedule 1"
        state: present
        unified_job_template: "Prueba"
        rrule: "DTSTART:20191219T130551Z RRULE:FREQ=WEEKLY;INTERVAL=1;COUNT=1"
      register: result
#  - include_role:
#      name: "nbu"
